# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    strategy:
      matrix:
        configuration: [ DEBUG, RELEASE ]
        os: [windows-latest, ubuntu-latest]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    container:
      image: 'novelrt/novelrt-build:latest'

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Checkout code'
        uses: actions/checkout@v2
        
        if: matrix.os == 'ubuntu-latest'
      - name: 'Run CI Build Script'
        run: '${GITHUB_WORKSPACE}/scripts/cibuild.sh --configuration ${{ matrix.configuration }}'

        if: matrix.os == 'windows-latest'
      - name: 'Run Windows Setup'
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        run: '%GITHUB_WORKSPACE%/scripts/machine-setup.cmd'
        shell: cmd
        
      - name: 'Run CI Build Script'
        run: '%GITHUB_WORKSPACE%/scripts/cibuild.cmd -configuration ${{ matrix.configuration }}'
        shell: cmd
