name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    name: ${{ matrix.os }}_${{ matrix.configuration }}_x64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        configuration: [DEBUG, RELEASE]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ubuntu - Run CI Build Script
        if: matrix.os == 'ubuntu-latest'
        run: %{GITHUB_WORKSPACE}/scripts/cibuild.sh --configuration ${{ matrix.configuration }}

      - name: Run Windows Setup
        if: (steps.cache-vcpkg.outputs.cache-hit != 'true' && matrix.os == 'windows-latest')
        run: %{GITHUB_WORKSPACE}/scripts/machine-setup.cmd
        shell: cmd

      - name: Run CI Build Script
        if: matrix.os == 'windows-latest'
        run: $GITHUB_WORKSPACE%/scripts/cibuild.cmd -configuration ${{ matrix.configuration }}
        shell: cmd
